# Generated by Django 2.2 on 2019-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bollywood_Actress_Name', models.CharField(default='', max_length=128)),
                ('Bollywood_Actor_Name', models.CharField(default='', max_length=128)),
                ('Body_Part_1', models.CharField(default='', max_length=128)),
                ('Body_Part_2', models.CharField(default='', max_length=128)),
                ('Old_Bollywood_Actor', models.CharField(default='', max_length=128)),
                ('Noun', models.CharField(default='', max_length=128)),
                ('Country', models.CharField(default='', max_length=128)),
                ('Occupation_1', models.CharField(default='', max_length=128)),
                ('Past_Tense_Verb', models.CharField(default='', max_length=128)),
                ('Occupation_2', models.CharField(default='', max_length=128)),
                ('Adjective_1', models.CharField(default='', max_length=128)),
                ('Adjective_2', models.CharField(default='', max_length=128)),
                ('Adjective_3', models.CharField(default='', max_length=128)),
                ('Number_between_1_and_10', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='story001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_name', models.CharField(default='', max_length=128)),
                ('verb_1', models.CharField(default='', max_length=128)),
                ('adjective_1', models.CharField(default='', max_length=128)),
                ('girl_name', models.CharField(default='', max_length=128)),
                ('movement', models.CharField(default='', max_length=128)),
                ('number_1', models.CharField(default='', max_length=128)),
                ('adjective_2', models.CharField(default='', max_length=128)),
                ('number_2', models.CharField(default='', max_length=128)),
                ('number_3', models.CharField(default='', max_length=128)),
                ('bollywood_actor', models.CharField(default='', max_length=128)),
                ('bollywood_film', models.CharField(default='', max_length=128)),
                ('adjective_3', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
