# Generated by Django 2.2 on 2019-04-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='Occupation',
            new_name='Occupation_1',
        ),
        migrations.AddField(
            model_name='story',
            name='Occupation_2',
            field=models.CharField(default='', max_length=128),
        ),
    ]
